package Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    FORGOT_PASSWORD,
    UPDATE_PASSWORD,
    UPDATE_USER,
    SEND_NOTIFICATIONS,
    UPDATE_ROLE,
    GET_ALL_USERS,
    UPDATE_ALL_USERS,
    GET_CONNECTED_USERS,
    LOGOUT,
    GET_ALL_DAYS,
    GET_REGION
}
