package Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    FORGOT_PASSWORD,
    UPDATE_USER,
    GET_ALL_USERS,
    UPDATE_ALL_USERS,
    GET_CONNECTED_USERS,
    LOGOUT,
    GET_ALL_DAYS,
    GET_REGION,
    TODAY_WEATHER,
    ADD_DAY,
    UPDATE_DAY,
    DELETE_DAY
}
