package Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    FORGOT_PASSWORD,
    UPDATE_PASSWORD,
    UPDATE_USER,
    SEND_NOTIFICATIONS,
    GET_ALL_USERS,
    UPDATE_ALL_USERS,
    GET_CONNECTED_USERS
}
